### 넘파이(numpy)
다차원 배열(행렬)을 쉽게 처리하고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리임<br>
수치 해석, 통계 관련 기능을 구현할 때 기본이 되는 모듈임<br>
Numerical Python의 줄임말임

In [4]:
!pip install numpy

In [32]:
import numpy as np

# 파이썬의 range()
# list(range(15))

# 넘파이 arange() - 1차원 벡터
x = np.arange(15)
print(x)
print(x.shape)

# 2차원 벡터(shape - 행렬의 크기)
x2 = x.reshape(3, 5)
print(x2)
print(x2.shape)

# 인덱싱 / 슬라이싱
print(x2[1:, :])

print(x2[1:, ::2])

x2[1:, ::2] = -99
print(x2)

print(x2.max())
print(x2.mean())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  7  9]
 [10 12 14]]
[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
13
-36.4


In [46]:
# 넘파이 - array() : 리스트 생성

a = [3, 1, 2]
x = np.array(a)
print(x)
print(type(x))
print(x.shape)

x2 = np.array([[1, 2, 3],
               [4, 5, 5]])
print(x2)
print(x2.shape)

[3 1 2]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 5]]
(2, 3)


In [56]:
a = [1.0, 2.0, 3.0]
b = [2.0, 4.0, 6.0]
print(a + b)
# print(a - b)

# numpy 연산
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[1.0, 2.0, 3.0, 2.0, 4.0, 6.0]
[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [66]:
# zero, one 행렬 생성
a = np.nan
print(a)
print(type(a))

a2 = np.zeros((3, 3))
print(a2)

a3 = np.ones((2, 3))
print(a3)

nan
<class 'float'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
